language: go
go_import_path: github.com/grokify/go-numverify
go:
  - "1.10.x"
  - "1.9.x"
  - "1.8.x"
  - "1.7.x"
  - "1.6.x"
  - "1.5.x"
  - "1.4.x"
  - tip
matrix:
  allow_failures:
    - go: "1.4.x"
    - go: tip
sudo: true
install:
  - go get -t -v ./...
script:
  - go test -v ./...
